# Generated by Django 4.0.1 on 2022-01-15 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Возрастной рейтинг',
                'verbose_name_plural': 'Возрастные рейтинги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Content_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Dubbing_studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Озвучка',
                'verbose_name_plural': 'Озвучки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VideoPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Плеер',
                'verbose_name_plural': 'Плееры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='IframeForContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('src', models.TextField()),
                ('number_of_episodes', models.IntegerField()),
                ('dubbing_studio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.dubbing_studio')),
                ('video_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.videoplayer')),
            ],
            options={
                'verbose_name': 'Iframe видео',
                'verbose_name_plural': 'Iframe видео',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('year', models.IntegerField()),
                ('season', models.CharField(blank=True, max_length=50)),
                ('original_source', models.CharField(blank=True, max_length=255)),
                ('studio', models.CharField(blank=True, max_length=255)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('Number_of_episodes', models.IntegerField()),
                ('synopsis', models.TextField(blank=True)),
                ('age_rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.age_rating')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.content_type')),
                ('dubbing_studio', models.ManyToManyField(blank=True, to='main.Dubbing_studio')),
                ('genre', models.ManyToManyField(blank=True, to='main.Genre')),
                ('iframe', models.ManyToManyField(blank=True, to='main.IframeForContent')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.status')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'ordering': ['-year'],
            },
        ),
    ]
