# Generated by Django 4.0.1 on 2022-02-06 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип списка',
                'verbose_name_plural': 'Типы списков',
            },
        ),
        migrations.AlterModelOptions(
            name='content_type',
            options={'ordering': ['title'], 'verbose_name': 'Тип аниме', 'verbose_name_plural': 'Типы аниме'},
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('hometown', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('update_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'Профиль ползователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='ContentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.content')),
                ('list_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.listtype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userprofiles')),
            ],
            options={
                'verbose_name': 'Cписок, объединённый',
                'verbose_name_plural': 'Cписок, объединённый',
            },
        ),
    ]
