# Generated by Django 4.0.1 on 2022-02-10 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_userprofiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d/'),
        ),
    ]
