# Generated by Django 4.0.1 on 2022-02-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_profile_contentlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtype',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
