# Generated by Django 4.0.1 on 2022-02-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_comments_options_alter_comments_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='father_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_father_comment', to='main.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='response_to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_response_to_comment', to='main.comments'),
        ),
    ]
