# Generated by Django 4.0.1 on 2022-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_comments_father_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='hometown',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d/'),
        ),
    ]
